[workspace]
resolver = "2"
members = [
  "assignments",
  "eppo_core",
  "rust-sdk",
  "python-sdk",
  "ruby-sdk/ext/eppo_client",
]

[patch.crates-io]
# Local override for development.
eppo_core = { path = './eppo_core' }
