// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.8.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'client.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

AttributeValue numericAttribute(double value) =>
    RustLib.instance.api.crateApiAttributesNumericAttribute(value: value);

AttributeValue categoricalNumberAttribute(double value) => RustLib.instance.api
    .crateApiAttributesCategoricalNumberAttribute(value: value);

AttributeValue stringAttribute(String value) =>
    RustLib.instance.api.crateApiAttributesStringAttribute(value: value);

AttributeValue boolAttribute(bool value) =>
    RustLib.instance.api.crateApiAttributesBoolAttribute(value: value);
