// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.8.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../api.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<AttributeValue>>
abstract class AttributeValue implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CoreClient>>
abstract class CoreClient implements RustOpaqueInterface {
  BanditResult banditAction(
      String flagKey,
      String subjectKey,
      Map<String, AttributeValue> subjectAttributes,
      Map<String, Map<String, AttributeValue>> actions,
      String defaultVariation);

  (bool?, Map<String, dynamic>?) booleanAssignment(String flagKey,
      String subjectKey, Map<String, AttributeValue> subjectAttributes);

  (int?, Map<String, dynamic>?) integerAssignment(String flagKey,
      String subjectKey, Map<String, AttributeValue> subjectAttributes);

  (String?, Map<String, dynamic>?) jsonAssignment(String flagKey,
      String subjectKey, Map<String, AttributeValue> subjectAttributes);

  factory CoreClient(
          {required String sdkKey,
          String baseUrl = r"https://fscdn.eppo.cloud/api",
          int pollIntervalMs = 30000,
          int pollJitterMs = 3000}) =>
      RustLib.instance.api.crateApiClientCoreClientNew(
          sdkKey: sdkKey,
          baseUrl: baseUrl,
          pollIntervalMs: pollIntervalMs,
          pollJitterMs: pollJitterMs);

  (double?, Map<String, dynamic>?) numericAssignment(String flagKey,
      String subjectKey, Map<String, AttributeValue> subjectAttributes);

  (String?, Map<String, dynamic>?) stringAssignment(String flagKey,
      String subjectKey, Map<String, AttributeValue> subjectAttributes);

  Future<void> waitForInitialization();
}
