[package]
name = "eppo_java"
version = "4.0.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
jni = "0.21.1"
eppo_core = { version = "4.1.0", features = ["vendored"] }
