// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.8.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class BanditResult {
  /// Selected variation from the feature flag.
  final String variation;

  /// Selected action if any.
  final String? action;

  /// Flag assignment event that needs to be logged to analytics storage.
  final Map<String, dynamic>? assignmentEvent;

  /// Bandit assignment event that needs to be logged to analytics storage.
  final Map<String, dynamic>? banditEvent;

  const BanditResult({
    required this.variation,
    this.action,
    this.assignmentEvent,
    this.banditEvent,
  });

  @override
  int get hashCode =>
      variation.hashCode ^
      action.hashCode ^
      assignmentEvent.hashCode ^
      banditEvent.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BanditResult &&
          runtimeType == other.runtimeType &&
          variation == other.variation &&
          action == other.action &&
          assignmentEvent == other.assignmentEvent &&
          banditEvent == other.banditEvent;
}
