# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in eppo-server-sdk.gemspec
gemspec

group :test do
  gem "rspec", "~> 3.0"
end

group :development do
  gem "rake", "~> 13.3"
  gem "rake-compiler"
  gem "rb_sys", "~> 0.9.119"
  gem "rubocop", "~> 1.81"
end
