name: Dart SDK

on:
  push:
    branches:
      - main
    tags:
      - "dart-sdk-*"
    paths:
      - "dart-sdk/**"
      - "eppo_core/**"
      - "sdk-test-data"
      - "mock-server/**"
      - "package-lock.json"
      - "package.json"
  pull_request:
    paths:
      - "dart-sdk/**"
      - "eppo_core/**"
      - "sdk-test-data"
      - "mock-server/**"
      - "package-lock.json"
      - "package.json"
  workflow_dispatch:

jobs:
  dart:
    name: Dart SDK
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for authentication using OIDC

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: dart-lang/setup-dart@v1
        with:
          sdk: 3.6

      - run: rustup update stable && rustup default stable
      - run: npm ci

      - name: Override eppo_core for testing
        # Released version should be built against published eppo_core
        if: "!startsWith(github.ref, 'refs/tags/dart-sdk-')"
        run: |
          mkdir -p "${CARGO_HOME:-$HOME/.cargo}"
          echo "[patch.crates-io.eppo_core]" >> "${CARGO_HOME:-$HOME/.cargo}/config.toml"
          echo "path = '$PWD/eppo_core'" >> "${CARGO_HOME:-$HOME/.cargo}/config.toml"

      - name: Install dependencies
        run: cargo install flutter_rust_bridge_codegen@=2.8.0 wasm-pack wasm-bindgen-cli cargo-expand

      - name: Run flutter codegen
        working-directory: dart-sdk
        run: flutter_rust_bridge_codegen generate --config-file flutter_rust_bridge.yaml

      - run: npm run with-server test:dart

      - name: Install toolchain for wasm build
        run: rustup toolchain install nightly -c rust-src

      - name: Build web
        run: flutter_rust_bridge_codegen build-web --release --wasm-pack-rustflags '--cfg getrandom_backend="wasm_js" -C target-feature=+atomics,+bulk-memory,+mutable-globals'
        working-directory: dart-sdk

      - uses: actions/upload-artifact@v4
        with:
          name: dart-sdk-web-files
          path: |
            dart-sdk/web/pkg/eppo_sdk.js
            dart-sdk/web/pkg/eppo_sdk_bg.wasm

      - name: Publish - dry run
        if: "!startsWith(github.ref, 'refs/tags/dart-sdk-')"
        run: dart pub publish --dry-run || true
        working-directory: dart-sdk

      - name: Refresh dart auth token
        if: "startsWith(github.ref, 'refs/tags/dart-sdk-')"
        uses: dart-lang/setup-dart@v1
        with:
          sdk: 3.6

      - name: Publish
        if: "startsWith(github.ref, 'refs/tags/dart-sdk-')"
        run: dart pub publish --force
        working-directory: dart-sdk
