name: Verify MSRV version

on:
  push:
    branches:
      - main
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  verify_msrv:
    name: Verify MSRV version
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git/db
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: |
          if ! command -v cargo-msrv &> /dev/null
          then
              cargo install cargo-msrv --locked
          fi
      - name: Verify MSRV for each package
        run: |
          for dir in eppo_core rust-sdk ruby-sdk/ext/eppo_client; do
            (cd $dir && cargo msrv verify)
          done
